name: Run Codember Challenges

on:
  push:
    branches:
      - 'main'

jobs:
  resolve-challenges:
    strategy:
      matrix:
        challenges: ['01']
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Prepare Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: ./challenges/${{ matrix.challenges }}
        run: |
          python -m pip install -U pip pytest
          pip install -r requirements.txt
      - name: Run integration tests
        working-directory: ./challenges/${{ matrix.challenges }}
        run: |
          pytest test.py
      - name: Run challenge
        working-directory: ./challenges/${{ matrix.challenges }}
        run: |
          python main.py
